// Mocks generated by Mockito 5.1.0 from annotations
// in myapp/test/src/widgets/detail/detail_title_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import '../book_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Book].
///
/// See the documentation for Mockito's code generation for more information.
class MockBook extends _i1.Mock implements _i2.Book {
  MockBook() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  set id(int? _id) => super.noSuchMethod(Invocation.setter(#id, _id),
      returnValueForMissingStub: null);
  @override
  String get title =>
      (super.noSuchMethod(Invocation.getter(#title), returnValue: '')
          as String);
  @override
  set title(String? _title) =>
      super.noSuchMethod(Invocation.setter(#title, _title),
          returnValueForMissingStub: null);
  @override
  int get review =>
      (super.noSuchMethod(Invocation.getter(#review), returnValue: 0) as int);
  @override
  set review(int? _review) =>
      super.noSuchMethod(Invocation.setter(#review, _review),
          returnValueForMissingStub: null);
  @override
  String get summary =>
      (super.noSuchMethod(Invocation.getter(#summary), returnValue: '')
          as String);
  @override
  set summary(String? _summary) =>
      super.noSuchMethod(Invocation.setter(#summary, _summary),
          returnValueForMissingStub: null);
  @override
  String get category =>
      (super.noSuchMethod(Invocation.getter(#category), returnValue: '')
          as String);
  @override
  set category(String? _category) =>
      super.noSuchMethod(Invocation.setter(#category, _category),
          returnValueForMissingStub: null);
  @override
  String get author =>
      (super.noSuchMethod(Invocation.getter(#author), returnValue: '')
          as String);
  @override
  set author(String? _author) =>
      super.noSuchMethod(Invocation.setter(#author, _author),
          returnValueForMissingStub: null);
  @override
  String get image =>
      (super.noSuchMethod(Invocation.getter(#image), returnValue: '')
          as String);
  @override
  set image(String? _image) =>
      super.noSuchMethod(Invocation.setter(#image, _image),
          returnValueForMissingStub: null);
  @override
  String get yearPublished =>
      (super.noSuchMethod(Invocation.getter(#yearPublished), returnValue: '')
          as String);
  @override
  set yearPublished(String? _yearPublished) =>
      super.noSuchMethod(Invocation.setter(#yearPublished, _yearPublished),
          returnValueForMissingStub: null);
}
